- name: Deploy DB and Web server
  hosts: db_server1,db_server2
  tasks: 
   - name: Install all required dependencies
     apt: name={{ item }} state=present
     with_items:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip

   - include: tasks/database_deployment.yml
   - include: tasks/web_deployment.yml